"""light_config table

Revision ID: c27ffcd4de5c
Revises: 
Create Date: 2018-11-17 18:25:05.762681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c27ffcd4de5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('light_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_light_config_name'), 'light_config', ['name'], unique=True)
    op.create_table('light_vals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.Integer(), nullable=True),
    sa.Column('config_name', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['config_name'], ['light_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_light_vals_color'), 'light_vals', ['color'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_light_vals_color'), table_name='light_vals')
    op.drop_table('light_vals')
    op.drop_index(op.f('ix_light_config_name'), table_name='light_config')
    op.drop_table('light_config')
    # ### end Alembic commands ###
